<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>sst-control-api</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SstControl.Application\SstControl.Application.csproj" />
    <ProjectReference Include="..\SstControl.Infrastructure\SstControl.Infrastructure.csproj" />
    <ProjectReference Include="..\SstControl.Integrations\SstControl.Integrations.csproj" />
  </ItemGroup>
</Project>
